#!/usr/bin/env perl

# The test script is written in Perl. It runs the peak_match program to compare the output file with the expected peak coordinates.
   


use strict;

my $expected_result="K169N-HN
M001N-HN
E168N-HN

T002N-HN
V109N-HN
R123N-HN
S136N-HN
K167N-HN
E063N-HN
K165N-HN
D108N-HN
Q061N-HN
G060N-HN
E049N-HN
K128N-HN

H166N-HN
R102N-HN
E031N-HN
";

# get the top 20 lines from file "assignment.txt", which is generated by the "peak_match" program
`./peak_match -in1 ass.list -in2 peaks_ass.tab`;

my $out = `head -20 assignment.txt`;

print($out);


my $return_code = 1; # code 1 means error, 0 means success

# if $out is the same as $expected_result, success
if($out eq $expected_result)
{
    $return_code = 0;
}

exit($return_code);
 
